/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exemplos;

import java.awt.BorderLayout;
import java.util.ArrayList;
import model.bean.Chamado;

/**
 *
 * @author Suporte-07
 */
public class GraficoTeste extends javax.swing.JFrame {

    /**
     * Creates new form GraficoTeste
     */
    public GraficoTeste() {
        initComponents();
        //importante
        this.Panel_Grafico.setLayout(new BorderLayout());
        /*
         FuncionarioDAO fdao = new FuncionarioDAO();
         ArrayList<Funcionario> list = fdao.getData((Empresa) combo_emp_cadFunc.getSelectedItem());
         model.setColumnIdentifiers(new Object[]{"ID", "Nome", "telefone", "Email", "Genero", "ID Empresa", "Nome Empresa", "Conexão", "AnyDesk"});
         Object[] row = new Object[9];
         for (int i = 0; i < list.size(); i++) {
         row[0] = list.get(i).getId_func();
         row[1] = list.get(i).getNome();
         row[2] = list.get(i).getTelefone();
         row[3] = list.get(i).getEmail();
         row[4] = list.get(i).getGenero();
         row[5] = list.get(i).getId_emp();
         row[6] = list.get(i).getNome_emp();
         row[7] = list.get(i).getConexao();
         row[8] = String.valueOf("Conexão");
         row[8] = AnyDesk(String.valueOf(list.get(i).getConexao()));
         model.addRow(row);
         }
         tbl_func.setModel(model);
         */
        ArrayList<Chamado> listadePessoas = new ArrayList<>();
        //listadePessoas.add(new Chamado[11,'willtunner']);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Grafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout Panel_GraficoLayout = new javax.swing.GroupLayout(Panel_Grafico);
        Panel_Grafico.setLayout(Panel_GraficoLayout);
        Panel_GraficoLayout.setHorizontalGroup(
            Panel_GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        Panel_GraficoLayout.setVerticalGroup(
            Panel_GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Panel_Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Panel_Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficoTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Grafico;
    // End of variables declaration//GEN-END:variables
}
